version: '3.7'

# note that there are no health checks yet so some containers will fail because databases are slow to start up
services:

  dbserver_entity:
    image: dbserver_entity
    # no exposed ports
    networks:
      - appnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  objectstore:
    image: objectstore
    ports:
      - 5555:5555
    networks:
      - appnetwork
    depends_on:
      - dbserver_entity
    restart: on-failure

  crudapp:
    image: crudapp
    ports:
      - 8000:8000
    networks:
      - appnetwork
    depends_on:
      - objectstore
    restart: on-failure

networks:
  appnetwork:

