version: '3.7'

# define secrets
secrets:
    mysql-root:
        file: mysqlrootpassword.txt

# define services. note that there is no need to specify build options
# because the names of the services match our subdirectories
services:

  dbserver_entity:
    image: dbserver_entity
    # no exposed ports
    networks:
      - appnetwork
    # use a secret
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
    # give access to a secret
    secrets:
      - mysql-root
    restart: on-failure

  objectstore:
    image: objectstore
    ports:
    # needs to be accessible from the browser as long as we don't have a reverse proxy
      - 5555:5555
    networks:
      - appnetwork
    # use a secret
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
    # give access to a secret
    secrets:
      - mysql-root
    depends_on:
      - dbserver_entity
    restart: on-failure

  crudapp:
    image: crudapp
    ports:
    # needs to be accessible from the browser, this is our main entry point
      - 8000:8000
    networks:
      - appnetwork
    depends_on:
      - objectstore
    restart: on-failure

networks:
  appnetwork:

