version: '3.7'

services:

  mywebapp:
    image: mywebapp
    command: --loghost dbserver
    networks:
      - appnetwork
# expose the webserver port on the same port on the host
    ports:
      - 8000:8000
    depends_on:
      - dbserver

# note that we have not created any volumes yet so nothing is saved 
  dbserver:
    image: mymysql
    # no exposed ports
    networks:
      - appnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  restapi:
    image: restapi
    ports:
      - 5555:5555
    networks:
      - appnetwork
    depends_on:
      - dbserver

# our network is external which means it should exist already
networks:
  appnetwork:
    external:
      name: appnetwork
